const appartments = [
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },

  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
  {
    appartmentName: "Landmark Rainforest",
    img: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img1: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img2: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img3: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    img4: "https://i.ibb.co/W0HJ7XY/Frist-pic.png",
    appartmentDescription: "",
    appartmentFor: "Sale",
    appartmentOwner: "Anwar Landmark Ltd",
    constructionStatus: "Constructed",
    transactionType: "New",
    bedroom: 4,
    balconies: 4,
    baths: 5,
    totalFloor: 9,
    facing: "East Facing",
    appartmentType: "Apartment/Flats",
    location: "Baridhara , Dhaka",
    appartmentSize: 3462,
    floorAvaiableOn: "3rd Floor, 4th Floor, 5th Floor",
    garages: 1,
    furnishing: "Furnished",
    landArea: 8.25,
  },
];
